### ISSUE TITLE
[Question] Trigger alarm from automation

### ISSUE THREAD

**Issue by renspr** [tschamm/boschshc-hass#117]
Is there a way to trigger the alarm from an automation?

I tried:
```
trigger:
  [snip]
condition:
  [snip]
action:
  - device_id: 5a5737d16598b757697aaf915ff2ed03
    domain: alarm_control_panel
    entity_id: fc93fc8d849a4edc5f453331047aae54
    type: trigger
```
and
```
trigger:
  [snip]
condition:
  [snip]
action:
  - service: alarm_control_panel.alarm_trigger
    data:
      entity_id: alarm_control_panel.intrusion_detection_system
```
 In both cases I get "Entity alarm_control_panel.intrusion_detection_system does not support this service" error.

Is this not implemented/possible with the integration or I'm doing something wrong?
