### ISSUE TITLE
Execute scenario from Home Assistant

### ISSUE THREAD

**Issue by geibenjamin** [tschamm/boschshc-hass#181]
Hi,
I defined multiple scenarios in the Bosch SmartHome App and would like to be able to execute those from Home Assistant. However, when trying to generate an automation, I only see SHC scenarios as a trigger, not as an actionable event.

Is this possible and I am doing something wrong or would it be possible to add that?

Thanks 
Benjamin

**Comment by mosandlt** [comment]
This is already supported — not via the automation *trigger* list, but as a **service** (action): `bosch_shc.trigger_scenario` with the scenario name.

Example (Developer Tools → Actions, or in an automation `action:` block):

```yaml
action: bosch_shc.trigger_scenario
data:
  name: "My Scenario"   # exactly as named in the Bosch Smart Home app
```

You can call that from any HA automation or script. (Current release 0.4.106.)
