### ISSUE TITLE
Kindersicherung für Raumthermostat (1. Generation)

### ISSUE THREAD

**Issue by Gloomyeye** [tschamm/boschshc-hass#194]
Hi,

ich habe das Bosch Smart Home Raumthermostat für Fußbodenheizungen 230V (1. Generation). Gibt es da eine Möglichkeit eine SWITCH Entität für die Kindersicherung zu erhalten? Ich sehe beim Gerät nur die Temperatur und Luftfeuchtigkeit.

Vielen Dank!

**Comment by mosandlt** [comment]
Eine **Kindersicherung**-Schalter-Entität für Thermostate wurde in **v0.4.104** ergänzt (`child_lock_thermostat` in `switch.py`, liest das `ChildLock`-Attribut).

Bitte über HACS auf die aktuelle Version (0.4.106) aktualisieren und HA neu starten — bei deinem Raumthermostat sollte dann ein „Child lock"/Kindersicherung-Schalter erscheinen. Falls er bei deinem 230 V Fußbodenthermostat (Gen 1) **nicht** auftaucht, poste bitte einen Rawscan des Geräts (das Gen-1-Modell meldet die Kindersicherung evtl. unter einem anderen Service) — dann ergänzen wir es. Wir lassen das offen, bis du testen konntest.

**Comment by Gloomyeye** [comment]
Hallo,

Nein, taucht leider nicht auf. Ich versuche mich mal am rawscan und teile das Ergebnis.

Vielen lieben Dank.

**Comment by mosandlt** [comment]
Super, danke! Den Rawscan bekommst du am einfachsten direkt aus Home Assistant — ohne Kommandozeile oder Zertifikat:

Entwicklerwerkzeuge → Aktionen → „Bosch SHC: Trigger rawscan", oben auf **YAML** umschalten und ausführen:
```yaml
action: bosch_shc.trigger_rawscan
data:
  command: devices
```
In der Antwort dein Raumthermostat (Gen 1, 230 V) suchen und dessen `"id"` kopieren (sieht aus wie `hdm:HomeMaticIP:...`). Dann:
```yaml
action: bosch_shc.trigger_rawscan
data:
  command: device_services
  device_id: <die id von oben>
```
Das Ergebnis hier reinkopieren (bitte vorher alles entfernen, was du als privat ansiehst). Daran sehen wir, unter welchem Service das Gen-1-Modell die Kindersicherung meldet, und können den passenden Schalter dafür ergänzen. Danke dir!

**Comment by Gloomyeye** [comment]
Hi, danke für die Anleitung. Ich erhalte folgende Meldung:

```
device_services:
  - "@type": DeviceServiceData
    id: Thermostat
    deviceId: hdm:HomeMaticIP:3014F711A000239D585EF318
    state:
      "@type": childLockState
      childLock: "ON"
    path: /devices/hdm:HomeMaticIP:3014F711A000239D585EF318/services/Thermostat
  - "@type": DeviceServiceData
    id: TemperatureLevel
    deviceId: hdm:HomeMaticIP:3014F711A000239D585EF318
    state:
      "@type": temperatureLevelState
      temperature: 26.2
    path: >-
      /devices/hdm:HomeMaticIP:3014F711A000239D585EF318/services/TemperatureLevel
  - "@type": DeviceServiceData
    id: HumidityLevel
    deviceId: hdm:HomeMaticIP:3014F711A000239D585EF318
    state:
      "@type": humidityLevelState
      humidity: 65
    path: /devices/hdm:HomeMaticIP:3014F711A000239D585EF318/services/HumidityLevel
  - "@type": DeviceServiceData
    id: CommunicationQuality
    deviceId: hdm:HomeMaticIP:3014F711A000239D585EF318
    state:
      "@type": communicationQualityState
      quality: GOOD
    path: >-
      /devices/hdm:HomeMaticIP:3014F711A000239D585EF318/services/CommunicationQuality
  - "@type": DeviceServiceData
    id: TemperatureOffset
    deviceId: hdm:HomeMaticIP:3014F711A000239D585EF318
    state:
      "@type": temperatureOffsetState
      offset: 0
      stepSize: 0.1
      minOffset: -3.5
      maxOffset: 3.5
    path: >-
      /devices/hdm:HomeMaticIP:3014F711A000239D585EF318/services/TemperatureOffset
  - "@type": DeviceServiceData
    id: WallThermostatConfiguration
    deviceId: hdm:HomeMaticIP:3014F711A000239D585EF318
    state:
      "@type": wallThermostatConfigurationState
      valveType: NORMALLY_CLOSE
      heaterType: FLOOR_HEATING
      supportedHeaterTypes:
        - RADIATOR
        - CONVECTOR_ACTIVE
        - CONVECTOR_PASSIVE
        - FLOOR_HEATING_LOW_ENERGY
        - FLOOR_HEATING
      decalcificationProtectionEnabled: true
    path: >-
      /devices/hdm:HomeMaticIP:3014F711A000239D585EF318/services/WallThermostatConfiguration
```

Reicht dieser Log?
