### ISSUE TITLE
Unable to set brightness value of smart dimmer to 1

### ISSUE THREAD

**Issue by nicodreher** [tschamm/boschshc-hass#208]
Hi,

I have an issue with the integration of the bosch smart dimmer.

When I try to set the brightness value to 1, I receive the following error: `SHC Error (message: API call returned non-OK result (code 400)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"INVALID_REQUEST_OBJECT","statusCode":400}')`

Setting it to 0 works and setting it to 2 also works. 

I suspect the issue is caused by the calculation of the percent value. Because the value 2 is converted to 1% and the value 1 to 0%. 

The API probably does not allow setting the brightness to 0%.

The action call:
```
action: light.turn_on
data:
  brightness: 1
target:
  entity_id: light.bedroom
```
