### ISSUE TITLE
HVAC mode of Bosch thermostat get set to automatic mode automatically

### ISSUE THREAD

**Issue by u20p17** [tschamm/boschshc-hass#65]
Hi all,
I am using Schedy (https://hass-apps.readthedocs.io/en/stable/apps/schedy/) for my heating schedule and it is working fine except one issue with the setting of the HVAC mode. As thermostats I am using the Bosch ones: https://www.bosch-smarthome.com/de/de/produkte/vorgaengermodelle/heizkoerper-thermostat/

![image](https://user-images.githubusercontent.com/63282286/199948394-b52c8b67-a592-4079-9182-2f172bd010b6.png)

As you can see in the image schedy changes the temperature to 17 deg. The HVAC mode get changed to automatic, then back to heat (what I would like to have) and finally back to automatic. Why? 

Furthermore it seems that the thermostat are only listening to the values send by Schedy if they are in the Heat HVAC mode. What values the thermostat is using when it is in automatic mode? I haven't defined any schedule in the Bosch app.

BR

**Comment by dolodobendan** [comment]
Not sure if it is related, but I see this with Tado:

![image](https://user-images.githubusercontent.com/37902856/200937705-f295393c-39b6-4f3e-86c6-20a5401b591f.png)

I don't know what caused the changes.

**Comment by arifroni** [comment]
I am also having this issue for some days. I have "better thermostat" to control the BOSCH thermostats II. When i set a temperature (eg: 22 ) with better thermostat, it goes to auto schedule and set target temperature as it is scheduled in bosch app. But i have turned of auto schedule in bosch app before.

**Comment by u20p17** [comment]
@tschamm: any idea what could be the problem or how we could debug into it? Would be nice that we could solve it :)

**Comment by tschamm** [comment]
Maybe the implementation for climate devices is not accepting changes from outside. I'll have a look in the next days.

**Comment by u20p17** [comment]
any news on this topic? :)

**Comment by arifroni** [comment]
could you update everything and check if this still exists? Yesterday I didn't notice this anymore.

**Comment by saxn-paule** [comment]
My thermostats work well with schedy without any issues. I use it in manual mode with HVAC disabled.

```
    child:
      friendly_name: Blubb
      allow_manual_changes: true
      rescheduling_delay: 60

      # All actors of this room go here.
      actors:
        climate.room_climate_kinderzimmer:
          delta: 0
          off_temp: 7.0
          supports_hvac_modes: false
```
